name: bitbucket_code_coverage
version: 0.0.2
description: >
  Converts coverage data from LCOV and publishes to Bitbucket server via
  Bitbucket Server Code Coverage plugin API.
homepage: https://github.com/arturdm/bitbucket_code_coverage

environment:
  sdk: '>=3.2.5 <4.0.0'

executables:
  bitbucket_code_coverage:

dependencies:
  args: ^2.4.2
  collection: ">=1.14.0 <2.0.0"
  glob: ^2.1.2
  http: ">=0.12.0 <1.0.0"
  json_annotation: ^4.8.1
  dlcov: ^4.2.1
  logging: ^1.2.0
  meta: ">=1.1.0 <2.0.0"
  path: ">=1.6.0 <2.0.0"
  quiver: ^3.2.1
  lcov_dart: 7.0.0

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  mock_web_server: ^5.0.0-nullsafety.1
  pedantic: ^1.4.0
  test: ^1.5.3
  test_cov_console: ^0.2.2
  test_descriptor: ^2.0.1
